### PR TITLE
Fixed issue with lost reference to a Tag when application is in backg…

### PR DESCRIPTION
**Pull request by ognjenmarcheta**
Fixed issue with lost reference to a Tag when the application is switched between background and foreground.

Issue:
https://github.com/revtel/react-native-nfc-manager/issues/433

### CODE REVIEW

**Comment by Bad-Listener** [comment]
Can we merge please? fixes a really annoying issue

**Comment by whitedogg13** [comment]
@Bad-Listener new version `3.10.1` has been released, please give it a try

**Comment by whitedogg13** [comment]
@ognjenmarcheta thanks for the contribution!

**Comment by Bad-Listener** [comment]
> @Bad-Listener new version `3.10.1` has been released, please give it a try

Everything works good now! Thanks a lot @whitedogg13 and @ognjenmarcheta !

**Pull request merged**
