### PR TITLE
feat(ios): support iso15693 sendRequest

### PR DESCRIPTION
**Pull request by whitedogg13**
This PR aims to support [iso15693 sendRequest for ios](https://developer.apple.com/documentation/corenfc/nfciso15693tag/3551933-sendrequestwithflag?language=objc).

`NfcManager.iso15693HandlerIOS.sendRequest` has been added, and the function signature is:

```typescript
sendRequest: (params: {
      flags: number;
      commandCode: number;
      data: number[];
    }) => Promise<[number, number[]]>;
```

The response tuple contains 2 elements:
- the first is `response flag`, see [Apple doc](https://developer.apple.com/documentation/corenfc/nfciso15693responseflag?language=objc)
- the second is `response data`, which is a byte array.

Regarding the first `response flag` value, it's also been exported as an enum in our `index.d.ts`:

```typescript
export enum Nfc15693ResponseFlagIOS {
    Error = 1 << 0,
    ResponseBufferValid = 1 << 1,
    FinalResponse = 1 << 2,
    ProtocolExtension = 1 << 3,
    BlockSecurityStatusBit5 = 1 << 4,
    BlockSecurityStatusBit6 = 1 << 5,
    WaitTimeExtension = 1 << 6,
}
```

### CODE REVIEW

**Comment by raydenvoldeskine** [comment]
Thanks, going to give you feedback in the next days.

**Comment by whitedogg13** [comment]
BTW @raydenvoldeskine we're also trying to provide a unified `NfcV` handler interface for both iOS and Android and it should be much easier to use compared to the current version. You can maybe hold on a bit regarding the test, thanks!

**Comment by raydenvoldeskine** [comment]
Understood. That what you mean is of course the more long-term solution.

**Comment by whitedogg13** [comment]
Hi @raydenvoldeskine we have provided a unified `NfcV` tech for both platforms. It works like this:

```javascript
try {
      await NfcManager.requestTechnology([NfcTech.NfcV]);
      const resp = await NfcManager.nfcVHandler.transceive(payload);
    } catch (ex) {
      console.warn(ex);
    } finally {
      NfcManager.cancelTechnologyRequest();
    }
```

The `nfcVHandler.transceive` will call `sendRequest:` for iOS and `transceive` for Android, and manipulate the param to allow two platforms to have the same behavior.

Please try it out using the latest `v3.13.0`, thanks!

**Comment by raydenvoldeskine** [comment]
Do you mean you have already released this change? Then it would be indeed easier to test.

**Comment by whitedogg13** [comment]
@raydenvoldeskine yes, it has been released. Please use `v3.13.0` to test.

**Comment by yfs-2000** [comment]
> @raydenvoldeskine yes, it has been released. Please use `v3.13.0` to test.

When I use NfcManager.nfcVHandler.transceive on ios I get an error saying at buildNfcExceptionIOS (NfcError.js:91:16)

**Pull request merged**
