### PR TITLE
fix: correct order of externalTypeRecord params

### PR DESCRIPTION
**Pull request by JdaieLin**

### CODE REVIEW

**Comment by whitedogg13** [comment]
@JdaieLin thanks for the catch!

**Comment by JdaieLin** [comment]
Is there a release for the next few days? @whitedogg13

**Comment by whitedogg13** [comment]
@JdaieLin `v3.13.1` just released, please give it a shot~

**Comment by JdaieLin** [comment]
amazing！0_0






------------------ Original ------------------
From: Richie ***@***.***&gt;
Date: Sun,Feb 6,2022 10:14 PM
To: revtel/react-native-nfc-manager ***@***.***&gt;
Cc: Jdaie ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [revtel/react-native-nfc-manager] fix: correct order of externalTypeRecord params (PR #490)





 
@JdaieLin v3.13.1 just released, please give it a shot~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
